apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfurl
  labels:
    app: pfurl
spec:
  selector:
    matchLabels:
      app: pfurl
  template:
    metadata:
      labels:
        app: pfurl
    spec:
      containers:
        - name: pfurl
          image: gcr.io/packetfire-218019/packetfire/pfurl:latest
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_ADDRESS
              value: 127.0.0.1:5432
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pfurl-postgres-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pfurl-postgres-db-credentials
                  key: password
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=packetfire-218019:us-east1:pfpg=tcp:5432",
		    "-credential_file=/secrets/cloudsql/key.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: pfurl-token
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: pfurl-token
          secret:
            secretName: pfurl-token
