version: '3'
services:
  pfurl:
    image: packetfire/pfurl
    build:
      context: ./
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_DB: pfurl
      POSTGRES_USER: pfurl
      POSTGRES_PASSWORD: pfurl
    ports:
      - "15432:5432"
    volumes:
      - ./run/pg:/var/lib/postgresql/data
    flyway-migrate:
    image: boxfuse/flyway:5.2.4-alpine
    command: -url=jdbc:postgresql://postgres:5432/pfurl -user=postgres -password=postgres migrate
    volumes:
      - ./migrations:/flyway/sql
    links:
      - postgres
    depends_on:
      - postgres
  flyway-clean:
    image: boxfuse/flyway:5.2.4-alpine
    command: -url=jdbc:postgresql://postgres:5432/pfurl -user=postgres -password=postgres clean
    volumes:
      - ./migrations:/flyway/sql
    links:
      - postgres
    depends_on:
      - postgres